# Numpy Operations

In [1]:
import numpy as np

In [5]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x=[1,2,3,4]

In [6]:
x+x

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr/arr

C:\Users\bakhtiyar kolzhabai\AppData\Local\Temp\ipykernel_7572\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1/arr

C:\Users\bakhtiyar kolzhabai\AppData\Local\Temp\ipykernel_7572\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Создание Array заданного интевала

сортировка производится от -3 до 3 по умолчанию при rand.randn.randint

In [20]:
np.random.rand(10) *6-3 #(-3,3)

array([-2.36688006,  1.06031293,  2.65202441, -1.88818142,  1.7208568 ,
        2.40062667,  0.02456871, -2.16492714,  2.24367458, -1.51191504])

In [23]:
np.random.randn(30)

array([ 2.20122408,  1.48233577, -1.40913877, -1.27999191,  0.02838664,
        1.09591042,  2.27447642, -0.07090327, -0.5668389 ,  1.5441357 ,
       -1.46474553,  0.9728075 , -1.58477289,  0.91671559,  0.99257873,
       -0.89645819, -1.26229156,  2.37589413,  1.39027804,  1.00154396,
       -0.07259136,  0.29472439, -0.4387504 ,  0.30831274,  0.24283778,
       -0.51523009, -0.73823804, -0.1345489 , -0.08851104,  0.56923109])

In [24]:
np.sort(np.random.randn(30))

array([-1.83923846, -1.69092093, -1.50191698, -1.22972384, -1.14772288,
       -1.01003129, -0.96659643, -0.96109525, -0.62531041, -0.62179261,
       -0.33570351, -0.25510487, -0.10725443, -0.0822622 , -0.01805287,
        0.11020286,  0.11318723,  0.31415851,  0.34225107,  0.42857277,
        0.5008788 ,  0.58365922,  0.64323518,  0.79186705,  0.80682887,
        1.14307993,  1.14416967,  1.67671216,  1.75172685,  1.81968565])

In [26]:
np.sort(np.random.rand(30) *7-3) #(-3,4)

array([-2.68754617, -2.33759839, -2.28158546, -2.0086163 , -1.80260161,
       -1.47146787, -1.12764421, -0.21356771,  0.0483541 ,  0.08851965,
        0.14626899,  0.44547835,  0.91202048,  1.03639578,  1.52951364,
        1.56044143,  1.67813436,  1.78696677,  1.94445962,  2.42137454,
        2.44406351,  2.45161805,  2.61414844,  2.64778504,  2.7574148 ,
        2.8448269 ,  2.85378831,  3.08082569,  3.10382524,  3.36849537])

In [27]:
sorted(np.random.rand(30) *7-3) #(-3,4)

[-2.8798743728363716,
 -2.6146352351712365,
 -2.5262358445200084,
 -2.5092483939551595,
 -2.055666028182777,
 -1.523927243384791,
 -1.4041865877335908,
 -0.9901155515999758,
 -0.2982422083127587,
 -0.2720632175027289,
 0.1485348150685053,
 0.2431889410229786,
 0.31934938731168305,
 0.33819024977822654,
 0.4524388051000696,
 0.9026571925688716,
 0.9538078439260986,
 1.0245134668677522,
 1.1109148970270217,
 1.7583764327314615,
 1.8675520899094034,
 2.4068948757519477,
 2.494957585687496,
 2.509764054639284,
 2.8569132952046807,
 2.8827037204912482,
 3.015040584444379,
 3.262174007627431,
 3.4451810778260255,
 3.625473852730802]

# Универсальные методы numpy array
используя модуль np работает на массивах, math только для одиночных

In [29]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [31]:
x=2
y=4

In [33]:
import math

In [34]:
math.sqrt(x)

1.4142135623730951

In [35]:
math.sqrt(y)

2.0

In [36]:
np.exp(arr)    # e**

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [37]:
np.max(arr)

9

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [39]:
np.log(arr)

C:\Users\bakhtiyar kolzhabai\AppData\Local\Temp\ipykernel_7572\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])