In [58]:
import numpy as np

In [59]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Индексация и выборка

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[7]

7

In [62]:
arr[1:5]

array([1, 2, 3, 4])

# Транслирование (Broadcasting)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr=arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [67]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [68]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr[:]=100
slice_of_arr

array([100, 100, 100, 100, 100])

In [70]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Индексация 2D массив

In [71]:
arr_2d=np.array([[5,10,15], [20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [73]:
arr_2d[2:]

array([[35, 40, 45]])

In [74]:
arr_2d[:,2:]

array([[15],
       [30],
       [45]])

# Интересные способы индексации

In [75]:
arr_2d=np.zeros((10,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
arr_2d.shape

(10, 10)

In [77]:
arr_lenght=arr_2d.shape[0]
arr_lenght

10

In [78]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
for i in range(arr_lenght):
    arr_2d[i]=i
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [80]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

# Создание матрицы от 1-49

In [81]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [82]:
np.arange(1,50).shape

(49,)

In [83]:
x=np.arange(1,50).reshape(7,7)
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [84]:
x[1:4,3:6]

array([[11, 12, 13],
       [18, 19, 20],
       [25, 26, 27]])

In [85]:
x[[1,3,5],3:-1]

array([[11, 12, 13],
       [25, 26, 27],
       [39, 40, 41]])

In [87]:
# Подумать выбрать матрицу по индексионно
x[[1,3,5],[1,3,5]]

array([ 9, 25, 41])

# Выбор фильтрация - Selection

In [93]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [95]:
bool_arr=arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [97]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# &-And , |-OR

In [98]:
(arr<5)&(arr!=4)

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [99]:
arr[(arr<5)&(arr!=4)]

array([1, 2, 3])

In [ ]:
#####